# Generated by Django 3.2.6 on 2021-08-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('es_usuario_admin', 'Acceso a herramientas del sitio'), ('es_super_admin', 'Acceso total al sitio')],
            },
        ),
    ]
