# Generated by Django 3.2.6 on 2021-08-23 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('visibilidad_perfil', models.BooleanField(default=False)),
                ('provincia', models.CharField(default='', max_length=50)),
                ('localidad', models.CharField(default='', max_length=50)),
                ('image', models.CharField(default='img/pic/profile1.png', max_length=30)),
                ('descripcion', models.CharField(default='Di lo que estás pensando.', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('es_usuario_admin', 'Acceso a herramientas del sitio'), ('es_super_admin', 'Acceso total al sitio')],
            },
        ),
    ]
