# Generated by Django 3.2.6 on 2021-08-07 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authusuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('visibilidad_perfil', models.BooleanField(default=False)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
    ]
