# Generated by Django 3.2.6 on 2021-08-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusuario', '0002_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='descripcion',
            field=models.CharField(default='Di lo que estás pensando.', max_length=500),
        ),
    ]
