# Generated by Django 3.2.6 on 2021-08-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusuario', '0004_auto_20210818_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='image',
            field=models.CharField(default='img/pic/profile1.png', max_length=30),
        ),
    ]
