# Generated by Django 3.2.6 on 2021-08-04 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juego_chaco', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='clasificacion',
        ),
    ]
