# Generated by Django 3.2.6 on 2021-08-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego_chaco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
