# Generated by Django 3.2.6 on 2021-08-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego_chaco', '0002_alter_partida_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
