# Generated by Django 3.2.6 on 2021-08-04 23:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('juego_chaco', '0002_remove_respuesta_clasificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
