# Generated by Django 3.2.6 on 2021-08-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego_chaco', '0003_partida_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='es_correcta',
            field=models.BooleanField(default=False),
        ),
    ]
