# Generated by Django 3.2.6 on 2021-08-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego_chaco', '0004_alter_respuesta_es_correcta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
