# Generated by Django 3.2.6 on 2021-08-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego_chaco', '0005_alter_pregunta_fecha_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='clasificacion',
            field=models.CharField(choices=[('Cultura y arte', 'Cultura'), ('Historia', 'Historia'), ('Geografía', 'Geografia'), ('Economía', 'Economia'), ('Ciencia y Educación', 'Ciencia'), ('Entretenimiento', 'Entretenimiento')], default='Geografía', max_length=30),
        ),
    ]
