# Generated by Django 3.2.6 on 2021-08-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego_chaco', '0006_alter_pregunta_clasificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='clasificacion',
            field=models.CharField(choices=[('CULTURA', 'Cultura'), ('HISTORIA', 'Historia'), ('GEOGRAFIA', 'Geografia'), ('ECONOMIA', 'Economia'), ('CIENCIA', 'Ciencia'), ('ENTRETENIMIENTO', 'Entretenimiento')], default='GEOGRAFIA', max_length=30),
        ),
    ]
